name: Update Dates and Meals JSON

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate combined JSON
        run: |
          node -e "
            const fs = require('fs');

            // Legge il file pasti.json
            let pasti = [];
            try {
              pasti = JSON.parse(fs.readFileSync('pasti.json', 'utf8'));
              if (!Array.isArray(pasti)) throw new Error('Formato pasti.json non valido');
            } catch (error) {
              console.log('Warning: pasti.json non trovato o non valido');
              pasti = [];
            }

            function getIndexWeek(jsDay) {
              return jsDay;
            }
            const oggi = new Date();
            const oggiIndex = getIndexWeek(oggi.getDay());

            const domani = new Date(oggi);
            domani.setDate(oggi.getDate() + 1);
            const domaniIndex = getIndexWeek(domani.getDay());

            // Array con i due pasti (oggi e domani), aggiungendo la data a ciascuno
            const risultati = [];
            const pOggi = pasti.find(p => p.indexWeek === oggiIndex);
            if (pOggi) {
              risultati.push({ ...pOggi, date: oggi.toISOString().split('T')[0] });
            }
            const pDomani = pasti.find(p => p.indexWeek === domaniIndex);
            if (pDomani) {
              risultati.push({ ...pDomani, date: domani.toISOString().split('T')[0] });
            }

            // Oggetto finale
            const out = {
              pasti: risultati,
              lastUpdate: new Date().toISOString()
            };

            fs.writeFileSync('lista-pasti.json', JSON.stringify(out, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add combined-data.json
          git commit -m "Update combined-data.json" || exit 0
          git push
